name:        evm-bytecode
version:     "0.0"
synopsis:    Parse Ethereum VM bytecode
license:     MIT
author:      Max Taldykin
maintainer:  <jorpic@gmail.com>
stability:   Not stable at all
category:    Language

dependencies:
  - base
  - bytestring
  - containers
  - largeword

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - QuasiQuotes

ghc-options:
  - -Wall
  - -Werror
  - -threaded
  - -O2
  - -funbox-strict-fields

library:
  source-dirs:
    - src/
  exposed-modules:
    - EVM.Instructions
